/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_LPUART1RXSRC_LPUART_RX 0x00u /*!<@brief LPUART1 Receive Data Source Select: LPUART1_RX pin */
#define SOPT5_LPUART1TXSRC_LPUART_TX 0x00u /*!<@brief LPUART1 Transmit Data Source Select: LPUART1_TX pin */

/*! @name PORTE30 (number 9), SEL_SW
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SEL_SW_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SEL_SW_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SEL_SW_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA19 (number 18), GPS_OUT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GPS_OUT_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPS_OUT_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPS_OUT_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTA18 (number 17), GPS_IN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GPS_IN_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPS_IN_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPS_IN_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC1 (number 22), VBAT
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_VBAT_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_VBAT_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_VBAT_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC2 (number 23), JUMPER_SW
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_JUMPER_SW_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_JUMPER_SW_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_JUMPER_SW_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_JUMPER_SW_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_JUMPER_SW_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_JUMPER_SW_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTC3 (number 24), LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTC5 (number 26), LORA_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LORA_SCK_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LORA_SCK_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LORA_SCK_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTC6 (number 27), LORA_MOSI
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LORA_MOSI_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LORA_MOSI_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LORA_MOSI_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTC7 (number 28), LORA_MISO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LORA_MISO_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LORA_MISO_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LORA_MISO_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTD4 (number 29), LORA_BUSY
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LORA_BUSY_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LORA_BUSY_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LORA_BUSY_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LORA_BUSY_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LORA_BUSY_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LORA_BUSY_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTD5 (number 30), LORA_DIO1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LORA_DIO1_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LORA_DIO1_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LORA_DIO1_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LORA_DIO1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LORA_DIO1_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LORA_DIO1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTC4 (number 25), LORA_CS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LORA_CS_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LORA_CS_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LORA_CS_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LORA_CS_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LORA_CS_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LORA_CS_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
